### ISSUE TITLE
Only one icon is visible on Andriod 8.0

### ISSUE THREAD

**Issue by uffejakobsen** [takke/cpustats#11]
Hi,
First a big thank you for cpustats - it is a really good tool 👍 

My OnePlus3T got Andriod 8.0 this weekend...

The cpustats application seems to work - but only shows one icon of the two possible in the notification bar.
The live graph is not visible anymore only the icon showing the core speed as a numver is shown.

**Comment by takke** [comment]
Thanks, but we can't support Android 8.0 or later due to the Android system limitation.

**Comment by uffejakobsen** [comment]
Thanks for your reply

What does that mean ? is the problem/limitation impossible to solve ?
Does this mean that the project dead/stopped ? 
And we should find another cpustat meter for Andriod 8 devices and forward ?

**Comment by takke** [comment]
>What does that mean ? is the problem/limitation impossible to solve ?

yes, impossible.

>Does this mean that the project dead/stopped ?

unfortunately yes.

>And we should find another cpustat meter for Andriod 8 devices and forward ?

yes, but may be nothing in the world of no-rooted devices.

**Comment by takke** [comment]
>What does that mean ? is the problem/limitation impossible to solve ?

yes, impossible.

>Does this mean that the project dead/stopped ?

unfortunately yes.

>And we should find another cpustat meter for Andriod 8 devices and forward ?

yes, but may be nothing in the world of no-rooted devices.

see https://issuetracker.google.com/issues/37140047

**Comment by uffejakobsen** [comment]
Ok, sad news - but thanks for your efforts - I really enjoyed your app the last years :-) 👍
