### ISSUE TITLE
After update to new version - CPUStats stops running when left idle

### ISSUE THREAD

**Issue by uffejakobsen** [takke/cpustats#15]
Hi,
After updating to new version 2.1.0
CPUStats starts and displays and updates the CPU activity fine in the notification bar.
But when I leave the phone "alone" for a few minuttes CPUstats notification bar icons are gone and does not come back...

Running on OnePlus 3T - Andriod 9.0 with all security updates (august 2019)

**Comment by uffejakobsen** [comment]
Further research shows that in my case the two notifications (the minuature bars and the frequency number) stays in the notification bar for aproximately 1 minuttes after starting CPUStats.
After what appears to be exact one minute the two notifications dissappear without any indication of what may have gone wrong...

**Comment by takke** [comment]
I released v2.1.1 today.

It may be fixed in v2.1.1, can you try it?

**Comment by uffejakobsen** [comment]
Yes it is much more stable now :+1: 

Thanks a lot for your quick response
I think this issue is closed
