### ISSUE TITLE
please add your own site/blog link and references to GitHub sources.

### ISSUE THREAD

**Issue by paulvi** [takke/cpustats#4]
aka About

**Comment by takke** [comment]
Added "About" activity
https://github.com/takke/cpustats/commit/1e4675b8562cea96aa935a45b816745500fd8bec

**Comment by paulvi** [comment]
Great, but I don't see link to GitHUb sources or your blog etc

**Comment by takke** [comment]
You can see the link to GitHub here.
![2015-04-20 00 00 33x](https://cloud.githubusercontent.com/assets/73930/7221928/ec23a154-e73b-11e4-8e5f-e82279850127.png)

**Comment by paulvi** [comment]
Oh, that looks great!
