### ISSUE TITLE
What do you use as network meter?

### ISSUE THREAD

**Issue by paulvi** [takke/cpustats#5]
What do you use as network meter?

> 0.9KB/s 3.7KB/s

![](https://cloud.githubusercontent.com/assets/73930/7221928/ec23a154-e73b-11e4-8e5f-e82279850127.png)

**Comment by takke** [comment]
It's my DataStats:
https://play.google.com/store/apps/details?id=jp.takke.datastats
https://github.com/takke/DataStats

**Comment by paulvi** [comment]
nice tools
